### ISSUE TITLE
torch distributed 초기화시 init_method 지정할 수 있는 옵션 추가하면 좋겠습니다

### ISSUE THREAD

**Issue by singleheart** [tunib-ai/oslo#8]
## Describe a requested feature

- oslo 현재 버전은 `init_method`가 TCP만 쓰도록 되어 있습니다. https://github.com/tunib-ai/oslo/blob/863bc8b30fba790d8803afe195d137d3a8ed3d0e/oslo/parallelism/mpu.py#L186
- 환경에 따라 `init_method`가 TCP면 `MASTER_PORT` 설정에도 불구하고 torch/distributed/rendezvous.py에서 `Address already in use` 에러가 발생할 수 있습니다.
- https://github.com/tunib-ai/oslo/blob/863bc8b30fba790d8803afe195d137d3a8ed3d0e/oslo/parallelism/mpu.py#L193 주석 처리하여 `init_method`를 쓰지 않도록 하면 이 문제는 해결 됩니다만, tcp가 필요한 환경도 있을 테니 옵션을 추가해서 다양한 설정을 받아들일 수 있으면 좋을 것 같습니다.

## Expected behavior

원본
```sh
$ PYTHONPATH=. python -m torch.distributed.launch --nproc_per_node 4 --nnodes 1 --node_rank 0 --master_addr localhost --master_port 6000 ./tests/gpt2/gpt2_test_tp_inference.py
...
생략
...
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=localhost
  master_port=6000
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1, 2, 3]
  role_ranks=[0, 1, 2, 3]
  global_ranks=[0, 1, 2, 3]
  role_world_sizes=[4, 4, 4, 4]
  global_world_sizes=[4, 4, 4, 4]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_gdjmg6p2/none__qzm5bjz/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_gdjmg6p2/none__qzm5bjz/attempt_0/1/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker2 reply file to: /tmp/torchelastic_gdjmg6p2/none__qzm5bjz/attempt_0/2/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker3 reply file to: /tmp/torchelastic_gdjmg6p2/none__qzm5bjz/attempt_0/3/error.json
Traceback (most recent call last):
  File "./tests/gpt2/gpt2_test_tp_training_with_ddp.py", line 278, in <module>
    test.test_gpt2_lm_head_model()
  File "./tests/gpt2/gpt2_test_tp_training_with_ddp.py", line 77, in test_gpt2_lm_head_model
    model_tp = GPT2LMHeadModel.from_pretrained_with_parallel(
  File "/home/singleheart/oslo/oslo/parallelism_utils.py", line 632, in from_pretrained_with_parallel
    cls._parallelize_from_model(
  File "/home/singleheart/oslo/oslo/parallelism_utils.py", line 329, in _parallelize_from_model
    cls._exec_both_engines(
  File "/home/singleheart/oslo/oslo/parallelism_utils.py", line 229, in _exec_both_engines
    mpu = MPU(
  File "/home/singleheart/oslo/oslo/parallelism/mpu.py", line 108, in __init__
    self.initialize_distributed()
  File "/home/singleheart/oslo/oslo/parallelism/mpu.py", line 191, in initialize_distributed
    torch.distributed.init_process_group(
  File "/home/singleheart/.pyenv/versions/oslo/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 520, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/singleheart/.pyenv/versions/oslo/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 142, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
```

https://github.com/tunib-ai/oslo/blob/863bc8b30fba790d8803afe195d137d3a8ed3d0e/oslo/parallelism/mpu.py#L193 주석 처리 후
```sh
$ PYTHONPATH=. python -m torch.distributed.launch --nproc_per_node 4 --nnodes 1 --node_rank 0 --master_addr localhost --master_port 6000 ./tests/gpt2/gpt2_test_tp_inference.py
...
생략
...
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=localhost
  master_port=6000
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1, 2, 3]
  role_ranks=[0, 1, 2, 3]
  global_ranks=[0, 1, 2, 3]
  role_world_sizes=[4, 4, 4, 4]
  global_world_sizes=[4, 4, 4, 4]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_l7adhxyx/none_l_xxkfso/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_l7adhxyx/none_l_xxkfso/attempt_0/1/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker2 reply file to: /tmp/torchelastic_l7adhxyx/none_l_xxkfso/attempt_0/2/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker3 reply file to: /tmp/torchelastic_l7adhxyx/none_l_xxkfso/attempt_0/3/error.json

TestTPInference:
--fp16:False
--test result: tensor([[False,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        ...,
        [ True,  True,  True,  ..., False,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ...,  True,  True,  True]], device='cuda:0')
```

위 예시에서는 port가 6000이지만, 포트 번호를 바꾸어도 결과는 각각 동일합니다.

## 참고자료
https://pytorch.org/docs/stable/distributed.html 설명에 따르면 초기화에 TCP, Shared file-system, Environment variable 세 가지가 있는데 환경변수를 통한 방법이 기본값이라고 되어 있고, 실제로 잘 작동합니다. 따라서 `init_method`를 지정하지 않는 옵션이 추가되면 좋을 것 같습니다.
```
This is the default method, meaning that init_method does not have to be specified (or can be env://).
```

**Comment by hyunwoongko** [comment]
안녕하세요.

https://github.com/tunib-ai/oslo/blob/master/oslo/parallelism/mpu.py#L107
여기 라인을 보시면 distributed initialization이 되어있지 않을때만 진행합니다.
따라서 원하시는 방식으로 미리 initialization을 수행하시면 이 코드가 실행되지 않습니다.

이 내용은 추후에 문서에 추가해놓겠습니다.
문제 생기면 코멘트 추가로 작성해주세요.

**Comment by singleheart** [comment]
`GPT2Model.from_pretrained_with_parallel()` 호출 전에 `torch.distributed.init_process_group()` 먼저 수행하니 잘 작동합니다. 감사합니다.
